#!/bin/bash

source src/qbit_user

qbit_service() {
  {
    sudo echo "[Unit]"
    sudo echo "Description=qBittorrent"
    sudo echo "After=network.target"
    sudo echo ""
    sudo echo "[Service]"
    sudo echo "Type=forking"
    sudo echo "ExecStart=/usr/bin/qbittorrent-nox -d --profile=~/ --webui-port=${portWeb}"
    sudo echo "Restart=on-failure"
    sudo echo ""
    sudo echo "[Install]"
    sudo echo "WantedBy=multi-user.target"
  } > /etc/systemd/system/qbittorrent-${portWeb}.service
}