#!/bin/bash

# Com isso ativado, ira baixar sua configuração do rclone já configurada.
# Requesito: Adicionar um link direto para download da sua conf.
rcloneDownloadConfig="off"
rcloneConfig=""

# Com isso ativado, seu RSS será adicionado e a organização de filmes, séries e etc feita.
# Requesitos: Adicionar seu link RSS.
rssEnable="off"
urlMoviesRSS=""
urlTvRSS="${urlMoviesRSS}"                        # Apague ${urlMoviesRSS} e adicione um link caso queira usar um RSS para cada categoria.

# Com isso ativado, todos os .torrents adicionados será salvo no seu drive.
# Requesito: criar um remote no rclone com nome de "files".
torrentsFileEnable="on"
filesRemote="Arquivos"

# Com isso ativado, seus arquivos torrents sera baixando do $filesRemote e adicionado no client.
# Opcional: Se "on", envie seus arquivos .torrents zipado no remote "files" para adicionar durante a instalação.
# O arquivo DEVE ter o nome de: torrents_latest.zip
autoTorrents="off"

# Adicionar remote para cursos
enableCourses="off"
courseRemote="Cursos"
coursePath="/cursos"
cacheCourses="100G"

# Com isso ativado, links simbólicos serão criando centralizando seus arquivos em uma única pasta.
# Requesito: autoTorrents ativado(on).
crontabEnable="on"
cronMovies="/*/*"                                 # Local onde seus filmes ira ficar. /*/* = $moviesPath/ano/file.mkv ou pasta
cronTv="/*"                                       # Local odne suas séries ira ficar. /* = $tvPath/Name.S01...
cronEps="/*"                                      # Local onde seus episódios avulsos ira ficar. /* = $epsPath/Name.S01E01...

# Pastas e arquivos do rclone.
moviesPath="/filmes"                              # Pasta onde sera montado o drive contendo os filmes.
tvPath="/series"                                  # Pasta onde sera montado o drive contendo as séries.
epsPath="/episodios"                              # Pasta onde sera montado o drive contendo os episódios.

# Nomes dos remote adicionados no rclone.
moviesRemote="Filmes"                             # Insira o nome que você inseriu no rclone para o remote de filmes.
tvRemote="Series"                                 # Insira o nome que você inseriu no rclone para o remote de séries.
epsRemote="Episodios"                             # Insira o nome que você inseriu no rclone para o remote de episódios.

# Local onde sera salvo os arquivos do rclone.
rcloneFilesDir="/home/$USER/rclone"

# Cache para os downloads feito pelo torrent.
# paga giga use "G", para mega usa "M".
cacheMovie="400G"                                 # Cache para filmes.
cacheTv="500G"                                    # Cache para séries.
cacheEps="100G"                                   # Cache para episódios.
cacheDir="${rcloneFilesDir}/cache"                # Diretorio onde o cache sera salvo

# Informações da maquina + random's
ip=$(curl -kLs "http://api.ipify.org")
portWeb=$(shuf -i 1000-10000 -n 1)
portQbit=$(shuf -i 1000-10000 -n 1)

# Script adicionais
# Scripts adicionado aqui será executado de antes de inicir a instalação.
qbit_onStart() {
  echo ""
  # Exemplo - Download SAs
  # wget LINKDIRETO -P /home/$USER/rclone/sas/
  # unzip /home/$USER/rclone/sas/sas.zip -d /home/$USER/rclone/sas/
  # rm /home/$USER/rclone/sas/sas.zip
  # sed -i "s|USER|$USER|g;" ${rcloneFilesDir}/config/rclone.conf
}

# Scripts adicionado aqui será executado após a instalação completa.
qbit_onEnd() {
  echo ""
}