#!/bin/bash

source src/qbit_user

qbit_rss() {
  if [ $rssEnable = "on" ]; then
    rssLink="~/qBittorrent/config/rss/feeds.json"
    {
      echo "{"
      echo "    \"Filmes\": {"
      echo "        \"url\": \"${urlMoviesRSS}\""
      echo "    },"
      echo "    \"Séries\": {"
      echo "        \"url\": \"${urlTvRSS}\""
      echo "    }"
      echo "}"
    } > ${rssLink}
  fi
}
