#!/bin/bash

source src/qbit_user

qbit_service() {
  {
    echo "[Unit]"
    echo "Description=qBittorrent"
    echo "After=network.target"
    echo ""
    echo "[Service]"
    echo "Type=forking"
    echo "ExecStart=/usr/bin/qbittorrent-nox -d --profile=/home/$USER --webui-port=${portWeb}"
    echo "Restart=on-failure"
    echo ""
    echo "[Install]"
    echo "WantedBy=multi-user.target"
  } > /etc/systemd/system/qbittorrent-${portWeb}.service
}