#!/bin/bash

source src/qbit_user

qbit_rclone () {
  service="/etc/systemd/system/"
  if [ ${enableCourses} = "on" ]; then
    serviceNames="${service}${moviesRemote}.service ${service}${tvRemote}.service ${service}${epsRemote}.service ${service}${courseRemote}.service"
  else
    serviceNames="${service}${moviesRemote}.service ${service}${tvRemote}.service ${service}${epsRemote}.service"
  fi
  for remotes in ${serviceNames}; do
    echo "[Unit]"                                                                           >  ${remotes}
    echo "Description=Rclone mount "                                                        >> ${remotes}
    echo "AssertPathIsDirectory=PATH"                                                       >> ${remotes}
    echo "After=network-online.target"                                                      >> ${remotes}
    echo ""                                                                                 >> ${remotes}
    echo "[Service]"                                                                        >> ${remotes}
    echo "Type=simple"                                                                      >> ${remotes}
    echo "ExecStart=/usr/bin/rclone mount \\"                                               >> ${remotes}
    echo "    --umask 0 \\"                                                                 >> ${remotes}
    echo "    --allow-other \\"                                                             >> ${remotes}
    echo "    --tpslimit 9 \\"                                                              >> ${remotes}
    echo "    --tpslimit-burst 10 \\"                                                       >> ${remotes}
    echo "    --transfers 8 \\"                                                             >> ${remotes}
    echo "    --checkers 16 \\"                                                             >> ${remotes}
    echo "    --config ${rcloneFilesDir}/config/rclone.conf \\"                             >> ${remotes}
    echo "    --dir-cache-time 672h \\"                                                     >> ${remotes}
    echo "    --vfs-cache-mode full \\"                                                     >> ${remotes}
    echo "    --vfs-cache-max-size CACHE \\"                                                >> ${remotes}
    echo "    --vfs-cache-max-age 675h \\"                                                  >> ${remotes}
    echo "    --vfs-read-chunk-size 4M \\"                                                  >> ${remotes}
    echo "    --vfs-read-chunk-size-limit 8M \\"                                            >> ${remotes}
    echo "    --drive-chunk-size 256M \\"                                                   >> ${remotes}
    echo "    --drive-stop-on-upload-limit \\"                                              >> ${remotes}
    echo "    --buffer-size 4M \\"                                                          >> ${remotes}
    echo "    --poll-interval 60s \\"                                                       >> ${remotes}
    echo "    --cache-dir ${cacheDir} \\"                                                   >> ${remotes}
    echo "    --log-file ${rcloneFilesDir}/logs/REMOTE \\"                                  >> ${remotes}
    echo "    --log-level INFO \\"                                                          >> ${remotes}
    echo "    REMOTE: PATH"                                                                 >> ${remotes}
    echo "ExecStop=/bin/fusermount -u PATH"                                                 >> ${remotes}
    echo "Restart=on-failure"                                                               >> ${remotes}
    echo "RestartSec=10"                                                                    >> ${remotes}
    echo ""                                                                                 >> ${remotes}
    echo "[Install]"                                                                        >> ${remotes}
    echo "WantedBy=default.target"                                                          >> ${remotes}
  done

  # Edita os serviços
  if [ ${enableCourses} = "on" ]; then
    sed -i "s|PATH|${coursePath}|g; s|CACHE|${cacheCourses}|g; s|REMOTE|${courseRemote}|g"  ${service}${courseRemote}.service
  fi
  sed -i "s|PATH|${moviesPath}|g; s|CACHE|${cacheMovie}|g; s|REMOTE|${moviesRemote}|g"      ${service}${moviesRemote}.service
  sed -i "s|PATH|${tvPath}|g; s|CACHE|${cacheTv}|g; s|REMOTE|${tvRemote}|g"                 ${service}${tvRemote}.service
  sed -i "s|PATH|${epsPath}|g; s|CACHE|${cacheEps}|g; s|REMOTE|${epsRemote}|g"              ${service}${epsRemote}.service
  systemctl daemon-reload

  # Cria pastas necessarias
  mkdir -p ${rcloneFilesDir}
  mkdir -p ${rcloneFilesDir}/logs

  # Verifica e cria as pasta do rclone.
  if [ ${enableCourses} = "on" ]; then
    pathRcloneCheck="${moviesPath} ${tvPath} ${epsPath} ${coursePath}"
  else
    pathRcloneCheck="${moviesPath} ${tvPath} ${epsPath}"
  fi
  for value in ${pathRcloneCheck}; do
    if [ ! -d "${value}" ]; then
      mkdir -p ${value}
    fi
  done

  # Inicia os serviços
  if [ ${rcloneDownloadConfig} = "on" ]; then
    systemctl enable ${moviesRemote}.service
    systemctl enable ${tvRemote}.service
    systemctl enable ${epsRemote}.service
    systemctl start ${moviesRemote}.service
    systemctl start ${tvRemote}.service
    systemctl start ${epsRemote}.service
    if [ ${enableCourses} = "on" ]; then
      systemctl enable ${courseRemote}.service
      systemctl start ${courseRemote}.service
    fi
  else
    systemctl enable ${moviesRemote}.service
    systemctl enable ${tvRemote}.service
    systemctl enable ${epsRemote}.service
    if [ ${enableCourses} = "on" ]; then
      systemctl enable ${courseRemote}.service
    fi
  fi

  # Verifica se o mount está correto
  if [ ${rcloneDownloadConfig} = "on" ]; then
    touch ${PWD}/check
    rclone copy ${PWD}/check ${moviesRemote}: --config ${rcloneFilesDir}/config/rclone.conf
    systemctl restart ${moviesRemote}.service
    echo "$(tput civis)"
    printf "\n\n\n"
    echo "Verificando mount, aguarde"
  while ! test -f "${moviesPath}/check"; do
    printf "."
    sleep 2
  done
    rm ${moviesPath}/check
    rm ${PWD}/check
  fi
  echo "$(tput cnorm)"

  # Cria pasta dos anos em $moviesPath
  if [ ${rcloneDownloadConfig} = "on" ]; then
    folder=1960
    while [ $folder -le 2021 ]; do
      if [ ! -d "$moviesPath/$folder" ]; then
        mkdir $moviesPath/$folder
        sleep 0.2
      fi
      folder=$(( $folder + 1 ))
    done
  fi
}